### ISSUE TITLE
posts.json not updating when new file added to content/posts directory

### ISSUE THREAD

**Issue by dmiyamasu** [themefisher/bookworm-light-nextjs#10]
I manually added a new .md file to the content/posts directory, and published it. The post page was created successfully, but the posts.json file was not updated to include that post content in the file. this results in the search functionality and "similar posts" functionality not working properly.

**Comment by tfsomrat** [comment]
Hello @dmiyamasu 

Thanks for choosing our template. posts.json creates when you run `npm run dev` or `npm run build`. If you want to update posts.json, then please cancel the dev command and run it again.
