### ISSUE TITLE
Custom blog slug

### ISSUE THREAD

**Issue by code-hyper** [themefisher/bookworm-light-nextjs#3]
Hi there, 

I'm newbie here. Just want some guide to have the blog post on sub pages instead on the homepage? For example - `domain.com/blog`

and homepage path "/" reserve for homepage content.

Looking forward to your reply.

Regards,
Codehyper

**Comment by mehedi-sharif** [comment]
Hey @code-hyper 

Thanks for your interest, actually it's a hard task to explain. and as you are a newbie, you won't understand this process.

**Comment by Mr-InamUrRahman** [comment]
hello this blog is very awesome. please can you add the comment section in single post page.
Thanks 
Regards
