### ISSUE TITLE
Please add the comment box in single post page

### ISSUE THREAD

**Issue by Mr-InamUrRahman** [themefisher/bookworm-light-nextjs#4]
Hi,

Thank you for making this pretty awesome blog, please can you add the comment box in single post page?

Thanks

**Comment by mehedi-sharif** [comment]
hey @Mr-InamUrRahman 

thanks for your interest. we have a plan to add this feature in the future. but we have a lot of tasks to complete before it. if you are willing to use this theme and add this feature to it, you can take our custom service at mehedi@themefisher.com [paid]

**Comment by piyushyadav0191** [comment]
Hi, Thank you for making this fantastic blog and as for the comment issue, I can suggest utteranc.es  because it can be configured easily in this blog.
