### ISSUE TITLE
How to add new posts

### ISSUE THREAD

**Issue by Sunno** [themefisher/bookworm-light-nextjs#5]
Hi, great theme! I was wondering what the process is to add a new post. I created a new MD file, and the Author page, but it doesn't appear on the page, neither the dev nor production build.

edit: it seems to be a bug, it appears if I have 6 or 8 posts, but not if there are 7

**Comment by mehedi-sharif** [comment]
Hello @Sunno 

Thanks for your concern. this issue has been fixed. please download the theme again to work correctly.
